### ISSUE TITLE
Error while converting a visa csv file

### ISSUE THREAD

**Issue by jukey** [hamvocke/dkb2homebank#1]
I will always get an error if I try to convert an exported visa csv file:

```
Traceback (most recent call last):
  File "./dkb2homebank/dkb2homebank.py", line 117, in <module>
    main()
  File "./dkb2homebank/dkb2homebank.py", line 107, in main
    convertVisa(args.filename)
  File "./dkb2homebank/dkb2homebank.py", line 78, in convertVisa
    'date': convertDate(row["wertstellung"]),
  File "./dkb2homebank/dkb2homebank.py", line 93, in convertDate
    date = datetime.strptime(dateString, "%d.%m.%Y")
TypeError: strptime() argument 1 must be string, not None
```

The file I used for the conversation attempt looks like that:

```
Kreditkarte:,1234********1234 Kreditkarte,,,,
,,,,,
Von:,02.07.2015,,,,
Bis:,30.06.2016,,,,
Saldo:,12345.67 EUR,,,,
Datum:,29.06.2016,,,,
,,,,,
Umsatz abgerechnet,Wertstellung,Belegdatum,Beschreibung,Betrag (EUR),Urspr�nglicher Betrag
Nein,29.06.2016,29.06.2016,buchung1,-1234,
Nein,24.06.2016,23.06.2016,buchung2,"11,79",
Ja,07.12.2015,04.12.2015,buchung in fremdwaehrung,"-41,82","-30,00 GBP"
Nein,06.12.2015,06.12.2015,buchung1,-1234,
Nein,24.11.2015,24.11.2015,buchung2,"11,79",
```

**Comment by hamvocke** [comment]
Thanks for reporting, @jukey!

Judging from the sample data you posted it seems like your CSV data is a little off from what I'm getting from my DKB exports. Did you do any additional modifications to this file or is this a "raw" CSV export from your DKB accounts?

**Comment by hamvocke** [comment]
Published a [new release](https://github.com/hamvocke/dkb2homebank/releases/tag/v0.1.1) that should fix your issue. I'd be happy to hear if this works out for you.

**Comment by jukey** [comment]
Hi @hamvocke the new version works like a charm! Thanks for the fast fix! :)

You are right. I opened the file using Libre Office and it seem to change the format slightly.

The "raw format"looks like this:

```
"Kreditkarte:";"1234********1234 Kreditkarte";

"Von:";"02.07.2015";
"Bis:";"30.06.2016";
"Saldo:";"1234.56 EUR";
"Datum:";"29.06.2016";

"Umsatz abgerechnet";"Wertstellung";"Belegdatum";"Beschreibung";"Betrag (EUR)";"Ursprünglicher Betrag
"Nein";"29.06.2016";"29.06.2016";"blubb";"-1.234,56";"";
```
